### ISSUE TITLE
Missing Code

### ISSUE THREAD

**Issue by hallo-kittyi** [ssecv/CoLA#1]
Hello, after reading your article, I am also very interested in the code part and want to further study and learn. I have downloaded the code you uploaded, but during the execution process, I found that two files such as pytorch_iou and clip were missing, may I ask if I can re-upload the complete code? Thank you very much.

**Comment by fengluo233** [comment]
Thank you for your interest! Our paper has recently been accepted, and we are in the process of organizing the code. We did overlook including some existing parts, but we will complete and upload them soon.

**Comment by fengluo233** [comment]
Hi, we've already update the code file and fix the bug!
