### ISSUE TITLE
Question of current code

### ISSUE THREAD

**Issue by fewroad** [ssecv/CoLA#2]
After reading your article, I want to implement the code, but I find that the code is different from that introduced in the paper, I want to know does the current code implement the LQA method mentioned in the paper. Hope for your reply.

**Comment by ssecv** [comment]
Thank you for your attention. The current code is from our previous submission, but we have since modified it for the ECCV24 version. We will update the code after the conference.

**Comment by fengluo233** [comment]
Hi, we've already update the code file and fix the bug!

**Comment by fewroad** [comment]
Thank you!
