### ISSUE TITLE
Questions about the model weight file

### ISSUE THREAD

**Issue by Angknpng** [ssecv/CoLA#3]
Hello. Your work is great!

Can you provide the training weights of the model for accurate testing?

**Comment by fengluo233** [comment]
Hi, we've already update the code file and fix the bug! And the checkpoints will be released soon through Google Drive.

**Comment by Angknpng** [comment]
okay, thanks! Waiting for it.

**Comment by fengluo233** [comment]
Hi, you can download the weights now!

**Comment by Angknpng** [comment]
Thank you very much!

**Comment by Angknpng** [comment]
hey, we find that the .pth files for RGB-D and RGB-T are same (i.e., rgb-t.pth) in the Baidu link. 

Could you please check it?

**Comment by fengluo233** [comment]
> hey, we find that the .pth files for RGB-D and RGB-T are same (i.e., rgb-t.pth) in the Baidu link.
> 
> Could you please check it?

Sorry, we have fix it, thanks for Comment!

**Comment by Angknpng** [comment]
Hello! We found that the performance of the rgb-d.pth file is very low, and **even the performance of Modality-Only-RGB is higher than that of Modality-Complete**. In addition, the performance of the rgb-t.pth file tested with the same code is correct.

Therefore, we think there is an error in the rgb-d.pth file. I hope you can check the rgb-d.pth file and update it for a more accurate comparison.
